name: build-and-test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: rake test
        env:
          test_api_key: ${{ secrets.SDK_E2E_TEST_COMPANY_API_KEY }}
          test_users: ${{ secrets.SDK_E2E_TEST_USERS }}
